/* ============================================================
   js/guest/products-data.js
   Central product catalogue — imported by browse & landing pages
   ============================================================ */

'use strict';

const ICON_PHOTO = `<svg class="w-8 h-8 text-white opacity-80" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>`;
const ICON_BANNER = `<svg class="w-8 h-8 text-white opacity-80" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 6h18M3 10h18m-9 4h9m-9 4h6"/></svg>`;
const ICON_FLYER  = `<svg class="w-8 h-8 text-white opacity-80" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>`;
const ICON_PRES   = `<svg class="w-8 h-8 text-white opacity-80" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z"/></svg>`;
const ICON_VIDEO  = `<svg class="w-8 h-8 text-white opacity-80" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M15 10l4.553-2.276A1 1 0 0121 8.723v6.554a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"/></svg>`;

const PRODUCTS = [
  // PRESENTATION
  { id: 1,  title: 'Nexus Corporate Deck',       category: 'presentation', price: 649,  rating: '4.9 (218)', downloads: 1204, desc: 'A sleek, modern pitch deck with 40+ fully editable slides. Perfect for startups and enterprise presentations with a professional dark theme.', author: 'by Pixeliize Studio', features: ['40+ Slides', 'PowerPoint & Keynote', 'Free Font Included', 'Fully Editable'], imgClass: 'img-pres',   icon: ICON_PRES   },
  { id: 2,  title: 'Aurora Creative Portfolio',  category: 'presentation', price: 499,  rating: '4.8 (156)', downloads: 890,  desc: 'Vibrant gradient-themed presentation template ideal for designers, artists, and creative agencies showcasing their portfolio.',              author: 'by Pixeliize Studio', features: ['35 Slides', 'PPTX + Google Slides', 'Animation Ready', 'Modern Layout'],       imgClass: 'img-pres',   icon: ICON_PRES   },
  { id: 3,  title: 'Minimal Business Report',    category: 'presentation', price: 349,  rating: '4.7 (203)', downloads: 762,  desc: 'Clean and minimal business report template. Ideal for quarterly reviews, financial summaries and corporate reporting.',                    author: 'by Pixeliize Studio', features: ['25 Slides', 'Infographic Elements', 'Data Visualization', 'Executive Summary'], imgClass: 'img-pres',   icon: ICON_PRES   },
  // PICTURE
  { id: 4,  title: 'Cinematic Portrait Edit',    category: 'picture',      price: 299,  rating: '5.0 (88)',  downloads: 412,  desc: 'Professional cinematic-style portrait retouching. Moody tones, clean skin, and dramatic lighting delivered as a layered PSD file.',       author: 'by Pixeliize Studio', features: ['PSD File Included', 'Layered Edit', 'Color Graded', 'Print Ready'],            imgClass: 'img-photo',  icon: ICON_PHOTO  },
  { id: 5,  title: 'Product Composite Pack',     category: 'picture',      price: 799,  rating: '4.9 (134)', downloads: 567,  desc: 'Professional product photo compositing with studio-grade backgrounds. Perfect for e-commerce and brand photography.',                    author: 'by Pixeliize Studio', features: ['5 Composites Included', 'White Background Option', 'Shadow Effects', 'High Res 300dpi'], imgClass: 'img-photo', icon: ICON_PHOTO },
  { id: 6,  title: 'Fashion Photo Retouch',      category: 'picture',      price: 450,  rating: '4.8 (97)',  downloads: 340,  desc: 'High-end fashion and lifestyle photo retouching. Skin smoothing, color correction, and background enhancement.',                         author: 'by Pixeliize Studio', features: ['Skin Retouching', 'Color Grade', 'Background Cleanup', 'Magazine Quality'],    imgClass: 'img-photo',  icon: ICON_PHOTO  },
  // BANNER
  { id: 7,  title: 'Summer Sale Banner Set',     category: 'banner',       price: 399,  rating: '4.8 (176)', downloads: 890,  desc: 'A complete set of 10 web banners in all standard sizes. Bright summer theme with editable text and colors in Photoshop.',               author: 'by Pixeliize Studio', features: ['10 Banner Sizes', 'Social Media Ready', 'Editable PSD', 'Web & Print'],       imgClass: 'img-banner', icon: ICON_BANNER },
  { id: 8,  title: 'Tech Startup Banner Pack',   category: 'banner',       price: 499,  rating: '4.9 (112)', downloads: 445,  desc: 'Dark tech-themed banner pack for SaaS startups and tech companies. Features glowing gradients and geometric patterns.',                  author: 'by Pixeliize Studio', features: ['8 Banner Variants', 'Dark & Light Versions', 'Vector Elements', 'Figma + PSD'], imgClass: 'img-banner', icon: ICON_BANNER },
  // FLYER
  { id: 9,  title: 'Club Night Event Flyer',     category: 'flyer',        price: 249,  rating: '4.7 (203)', downloads: 1120, desc: 'High-energy neon club flyer for events, parties, and nightlife promotions. Fully customizable text and colors.',                         author: 'by Pixeliize Studio', features: ['A4 + Letter Size', 'Neon Effects', 'Font Included', 'Print Ready 300dpi'],   imgClass: 'img-flyer',  icon: ICON_FLYER  },
  { id: 10, title: 'Business Services Flyer',    category: 'flyer',        price: 199,  rating: '4.8 (89)',  downloads: 678,  desc: 'Clean and professional flyer template for business services, consulting, and corporate events.',                                          author: 'by Pixeliize Studio', features: ['Clean Layout', 'Corporate Style', 'Editable PSD', 'Front & Back'],            imgClass: 'img-flyer',  icon: ICON_FLYER  },
  // VIDEO
  { id: 11, title: 'Cinematic Brand Intro',      category: 'video',        price: 1299, rating: '5.0 (67)',  downloads: 234,  desc: 'Stunning 10-second cinematic brand intro for YouTube, Instagram, or any video content. Delivered as MP4 with customizable text.',        author: 'by Pixeliize Studio', features: ['10s Duration', '4K Resolution', 'Multiple Versions', 'After Effects Source'], imgClass: 'img-video',  icon: ICON_VIDEO  },
  { id: 12, title: 'Social Reel Edit Pack',      category: 'video',        price: 999,  rating: '4.9 (145)', downloads: 489,  desc: 'Professional social media reel edits in vertical format. Dynamic transitions, text overlays, and music sync ready.',                     author: 'by Pixeliize Studio', features: ['3 Reel Formats', '9:16 Vertical', 'Transition Pack', 'CapCut & Premiere'],   imgClass: 'img-video',  icon: ICON_VIDEO  },
];
